/**
 * Every string the 제주 waiting games draw, in the kiosk's eight languages.
 *
 * Authored here rather than synced from Localization_Jeju for the same reason
 * JejuSpotDiffGame authors its own: there are no sheet rows for these screens,
 * and an unmapped key renders Korean to every non-Korean visitor. Move them to
 * the sheet the day the operators add the rows — `pick()` does not care where
 * the map came from.
 *
 * Read with `pick(TEXT.someKey, lang)`. Korean is the fallback, so a language
 * may be omitted; none are, deliberately — a half-translated game screen is the
 * exact thing the 제주공항 audience notices.
 */
import type { Lang } from '@renderer/lib/i18n';

type Str = Partial<Record<Lang, string>>;

export const TEXT = {
  // ── Hub ───────────────────────────────────────────────────────────────
  hubTitle: {
    ko: '제주 게임',
    en: 'JEJU GAMES',
    ja: '済州ゲーム',
    zh: '济州游戏',
    vi: 'TRÒ CHƠI JEJU',
    th: 'เกมเชจู',
    ru: 'ИГРЫ ЧЕДЖУ',
    id: 'GIM JEJU',
  } as Str,
  hubSubtitle: {
    ko: '기다리는 동안 게임하고 제주도 만나보세요!',
    en: 'Play a quick game and explore Jeju!',
    ja: 'お待ちの間にゲームで済州を楽しもう！',
    zh: '等待时玩个小游戏，认识济州！',
    vi: 'Chơi game nhanh và khám phá Jeju!',
    th: 'เล่นเกมสั้น ๆ แล้วมารู้จักเชจู!',
    ru: 'Сыграйте, пока ждёте, и узнайте Чеджу!',
    id: 'Main gim singkat dan jelajahi Jeju!',
  } as Str,
  points: {
    ko: '제주 포인트',
    en: 'JEJU POINTS',
    ja: '済州ポイント',
    zh: '济州积分',
    vi: 'ĐIỂM JEJU',
    th: 'แต้มเชจู',
    ru: 'ОЧКИ ЧЕДЖУ',
    id: 'POIN JEJU',
  } as Str,

  /** Section heading over the finger-on-glass games. */
  touchGames: {
    ko: '터치 게임',
    en: 'TOUCH GAMES',
    ja: 'タッチゲーム',
    zh: '触屏游戏',
    vi: 'TRÒ CHƠI CẢM ỨNG',
    th: 'เกมสัมผัส',
    ru: 'СЕНСОРНЫЕ ИГРЫ',
    id: 'GIM SENTUH',
  } as Str,
  /** Section heading over the camera games — see the note in JejuGameHub. */
  motionGames: {
    ko: '몸으로 하는 게임',
    en: 'MOTION GAMES',
    ja: '体で遊ぶゲーム',
    zh: '体感游戏',
    vi: 'TRÒ CHƠI VẬN ĐỘNG',
    th: 'เกมขยับตัว',
    ru: 'ИГРЫ ДВИЖЕНИЯ',
    id: 'GIM GERAK',
  } as Str,

  // ── Game cards ────────────────────────────────────────────────────────
  catchName: {
    ko: '감귤 받기',
    en: 'Tangerine Catch',
    ja: 'みかんキャッチ',
    zh: '接柑橘',
    vi: 'Hứng Quýt',
    th: 'รับส้มเชจู',
    ru: 'Лови мандарины',
    id: 'Tangkap Jeruk',
  } as Str,
  catchDesc: {
    ko: '떨어지는 감귤을 바구니로 받아요!',
    en: 'Catch as many tangerines as you can!',
    ja: '落ちてくるみかんをカゴでキャッチ！',
    zh: '用篮子接住掉落的柑橘！',
    vi: 'Hứng thật nhiều quýt rơi xuống!',
    th: 'รับส้มที่ร่วงลงมาให้ได้มากที่สุด!',
    ru: 'Ловите падающие мандарины корзиной!',
    id: 'Tangkap jeruk yang jatuh sebanyak mungkin!',
  } as Str,
  cupName: {
    ko: '감귤은 어디에?',
    en: "Where's the Tangerine?",
    ja: 'みかんはどこ？',
    zh: '柑橘在哪里？',
    vi: 'Quýt Ở Đâu?',
    th: 'ส้มอยู่ไหน?',
    ru: 'Где мандарин?',
    id: 'Di Mana Jeruknya?',
  } as Str,
  cupDesc: {
    ko: '잘 보고 감귤이 숨은 컵을 찾아요!',
    en: 'Watch carefully and find the tangerine!',
    ja: 'よく見てみかんの隠れたカップを当てよう！',
    zh: '看仔细，找出藏着柑橘的杯子！',
    vi: 'Nhìn kỹ và tìm chiếc cốc giấu quýt!',
    th: 'ดูให้ดีแล้วหาแก้วที่ซ่อนส้ม!',
    ru: 'Следите внимательно и найдите мандарин!',
    id: 'Perhatikan baik-baik dan temukan jeruknya!',
  } as Str,
  spotDiffName: {
    ko: '틀린 그림 찾기',
    en: 'Spot the Difference',
    ja: '間違い探し',
    zh: '找不同',
    vi: 'Tìm Điểm Khác',
    th: 'หาจุดต่าง',
    ru: 'Найди отличия',
    id: 'Cari Perbedaan',
  } as Str,
  spotDiffDesc: {
    ko: '두 그림에서 다른 곳을 찾아보세요!',
    en: 'Spot what changed between two pictures!',
    ja: '2枚の絵の違いを見つけよう！',
    zh: '找出两幅图中的不同之处！',
    vi: 'Tìm điểm khác giữa hai bức tranh!',
    th: 'หาจุดที่ต่างกันของสองภาพ!',
    ru: 'Найдите отличия между картинками!',
    id: 'Temukan perbedaan dua gambar!',
  } as Str,

  // ── Shared HUD / buttons ──────────────────────────────────────────────
  score: {
    ko: '점수',
    en: 'SCORE',
    ja: 'スコア',
    zh: '得分',
    vi: 'ĐIỂM',
    th: 'คะแนน',
    ru: 'ОЧКИ',
    id: 'SKOR',
  } as Str,
  timeLeft: {
    ko: '남은 시간',
    en: 'TIME LEFT',
    ja: '残り時間',
    zh: '剩余时间',
    vi: 'THỜI GIAN',
    th: 'เวลาที่เหลือ',
    ru: 'ВРЕМЯ',
    id: 'SISA WAKTU',
  } as Str,
  playAgain: {
    ko: '한 판 더!',
    en: 'Play again',
    ja: 'もう一回！',
    zh: '再玩一次！',
    vi: 'Chơi lại!',
    th: 'เล่นอีกครั้ง!',
    ru: 'Ещё раз!',
    id: 'Main lagi!',
  } as Str,
  backToGames: {
    ko: '다른 게임',
    en: 'Back to Games',
    ja: '他のゲーム',
    zh: '其他游戏',
    vi: 'Trò chơi khác',
    th: 'เกมอื่น',
    ru: 'Другие игры',
    id: 'Gim lain',
  } as Str,
  seePhoto: {
    ko: '사진 보기',
    en: 'See my photo',
    ja: '写真を見る',
    zh: '查看照片',
    vi: 'Xem ảnh',
    th: 'ดูรูปของฉัน',
    ru: 'Посмотреть фото',
    id: 'Lihat foto',
  } as Str,
  tapToStart: {
    ko: '화면을 눌러 시작하세요',
    en: 'Touch the screen to start',
    ja: '画面をタッチしてスタート',
    zh: '点击屏幕开始',
    vi: 'Chạm màn hình để bắt đầu',
    th: 'แตะหน้าจอเพื่อเริ่ม',
    ru: 'Коснитесь экрана, чтобы начать',
    id: 'Sentuh layar untuk mulai',
  } as Str,
  go: {
    ko: '시작!',
    en: 'GO!',
    ja: 'スタート！',
    zh: '开始！',
    vi: 'BẮT ĐẦU!',
    th: 'เริ่ม!',
    ru: 'СТАРТ!',
    id: 'MULAI!',
  } as Str,

  // ── Photo status (shown on the hub while the AI works) ────────────────
  photoWorking: {
    ko: 'AI가 사진을 만들고 있어요',
    en: 'The AI is making your photo',
    ja: 'AIが写真を作っています',
    zh: 'AI正在生成您的照片',
    vi: 'AI đang tạo ảnh của bạn',
    th: 'AI กำลังสร้างภาพของคุณ',
    ru: 'ИИ создаёт ваше фото',
    id: 'AI sedang membuat foto Anda',
  } as Str,
  photoReady: {
    ko: '사진이 완성됐어요!',
    en: 'Your photo is ready!',
    ja: '写真が完成しました！',
    zh: '照片已完成！',
    vi: 'Ảnh của bạn đã xong!',
    th: 'ภาพของคุณพร้อมแล้ว!',
    ru: 'Ваше фото готово!',
    id: 'Foto Anda siap!',
  } as Str,

  // ── Tangerine Catch ───────────────────────────────────────────────────
  catchHowTo: {
    ko: '바구니를 움직여 감귤을 받으세요',
    en: 'Drag the basket to catch the tangerines',
    ja: 'カゴを動かしてみかんを受けよう',
    zh: '移动篮子接住柑橘',
    vi: 'Kéo giỏ để hứng quýt',
    th: 'ลากตะกร้าเพื่อรับส้ม',
    ru: 'Двигайте корзину и ловите мандарины',
    id: 'Geser keranjang untuk menangkap jeruk',
  } as Str,
  catchResultTitle: {
    ko: '잘 받았어요!',
    en: 'Great Catch!',
    ja: 'ナイスキャッチ！',
    zh: '接得漂亮！',
    vi: 'Hứng giỏi lắm!',
    th: 'รับได้เยี่ยม!',
    ru: 'Отличный улов!',
    id: 'Tangkapan hebat!',
  } as Str,
  catchCount: {
    ko: '개를 받았어요',
    en: 'caught',
    ja: '個キャッチ',
    zh: '个已接住',
    vi: 'quả đã hứng',
    th: 'ลูกที่รับได้',
    ru: 'поймано',
    id: 'buah tertangkap',
  } as Str,

  // ── Where's the Tangerine ─────────────────────────────────────────────
  cupWatch: {
    ko: '잘 보세요! 👀',
    en: 'Watch carefully! 👀',
    ja: 'よく見てね！ 👀',
    zh: '看仔细！ 👀',
    vi: 'Nhìn kỹ nhé! 👀',
    th: 'ดูให้ดีนะ! 👀',
    ru: 'Следите внимательно! 👀',
    id: 'Perhatikan baik-baik! 👀',
  } as Str,
  cupShuffling: {
    ko: '섞는 중…',
    en: 'Shuffling…',
    ja: 'シャッフル中…',
    zh: '正在洗牌…',
    vi: 'Đang xáo trộn…',
    th: 'กำลังสลับ…',
    ru: 'Перемешиваем…',
    id: 'Mengacak…',
  } as Str,
  cupChoose: {
    ko: '감귤은 어디에? 🍊',
    en: "Where's the 🍊?",
    ja: 'みかんはどこ？ 🍊',
    zh: '柑橘在哪里？ 🍊',
    vi: 'Quýt ở đâu? 🍊',
    th: 'ส้มอยู่ไหน? 🍊',
    ru: 'Где 🍊?',
    id: 'Di mana 🍊?',
  } as Str,
  cupCorrect: {
    ko: '찾았어요! 🍊',
    en: 'You found it! 🍊',
    ja: '見つけた！ 🍊',
    zh: '找到了！ 🍊',
    vi: 'Bạn tìm ra rồi! 🍊',
    th: 'เจอแล้ว! 🍊',
    ru: 'Вы нашли! 🍊',
    id: 'Kamu menemukannya! 🍊',
  } as Str,
  cupWrong: {
    ko: '아쉬워요! 😄',
    en: 'Almost! 😄',
    ja: '惜しい！ 😄',
    zh: '差一点！ 😄',
    vi: 'Suýt nữa! 😄',
    th: 'เกือบแล้ว! 😄',
    ru: 'Почти! 😄',
    id: 'Hampir! 😄',
  } as Str,
  cupWasHere: {
    ko: '감귤은 여기 있었어요!',
    en: 'The tangerine was here!',
    ja: 'みかんはここでした！',
    zh: '柑橘在这里！',
    vi: 'Quýt ở đây!',
    th: 'ส้มอยู่ตรงนี้!',
    ru: 'Мандарин был здесь!',
    id: 'Jeruknya ada di sini!',
  } as Str,
  cupRound: {
    ko: '라운드',
    en: 'ROUND',
    ja: 'ラウンド',
    zh: '回合',
    vi: 'VÒNG',
    th: 'รอบ',
    ru: 'РАУНД',
    id: 'RONDE',
  } as Str,
  cupResultTitle: {
    ko: '게임 끝!',
    en: 'Game over!',
    ja: 'ゲーム終了！',
    zh: '游戏结束！',
    vi: 'Kết thúc!',
    th: 'จบเกม!',
    ru: 'Игра окончена!',
    id: 'Permainan selesai!',
  } as Str,
  cupCorrectCount: {
    ko: '번 맞혔어요',
    en: 'correct',
    ja: '回正解',
    zh: '次答对',
    vi: 'lần đúng',
    th: 'ครั้งที่ถูก',
    ru: 'верно',
    id: 'kali benar',
  } as Str,
} as const;
