// AUTO-GENERATED by scripts/sync-sheet.mjs — do not edit by hand.
// Run `npm run sync:sheet` to refresh from the Google Sheet.
import type { LangText } from './types';

/** '인사' 뭐하지 (AI검색) — 즐길거리 categories, prefix stripped. */
export const AI_CATEGORIES: LangText[] = [
  {"ko":"코리안바베큐","en":"Korean BBQ","ja":"韓国のバーベキュー","zh":"韩国烧烤","vi":"BBQ Hàn Quốc","th":"บาร์บีคิวเกาหลี","ru":"Корейское барбекю","id":"BBQ Korea"},
  {"ko":"한식","en":"Korean food","ja":"韓国料理","zh":"韩国菜","vi":"Món ăn Hàn Quốc","th":"อาหารเกาหลี","ru":"Корейская кухня","id":"Makanan Korea"},
  {"ko":"한정식","en":"Course meal","ja":"韓定食","zh":"韩定食","vi":"Hanjeongsik","th":"ฮันจองชิก","ru":"Ханджонсик","id":"Hanjeongsik"},
  {"ko":"분식","en":"Street Food","ja":"韓国の軽食","zh":"韩国小吃","vi":"Thức ăn đường phố","th":"อาหารริมทาง","ru":"Уличная еда","id":"Jajanan Kaki Lima"},
  {"ko":"사찰음식","en":"Temple Food","ja":"査察料理","zh":"寺庙食物","vi":"Thức ăn chùa","th":"อาหารวัด","ru":"Храмовая еда","id":"Makanan Kuil"},
  {"ko":"채식/비건","en":"Vegetarian","ja":"ベジタリアン/ビーガン","zh":"素食/纯素食","vi":"Ăn chay/Thuần chay","th":"มังสวิรัติ/เจ","ru":"Вегетарианская/Веганская еда","id":"Vegetarian/Vegan"},
  {"ko":"아시안","en":"Asian","ja":"アジア","zh":"亚洲人","vi":"Món ăn Châu Á","th":"อาหารเอเชีย","ru":"Азиатская кухня","id":"Makanan Asia"},
  {"ko":"중식","en":"Chinese food","ja":"昼食","zh":"午餐","vi":"Món ăn Trung Quốc","th":"อาหารจีน","ru":"Китайская кухня","id":"Makanan Tionghoa"},
  {"ko":"전통차","en":"Traditional Tea","ja":"伝統的な車","zh":"传统茶","vi":"Trà truyền thống","th":"ชาแบบดั้งเดิม","ru":"Традиционный чай","id":"Teh Tradisional"},
  {"ko":"카페","en":"Cafe","ja":"カフェ","zh":"咖啡馆","vi":"Quán cà phê","th":"คาเฟ่","ru":"Кафе","id":"Kafe"},
  {"ko":"의류","en":"Clothing","ja":"衣類","zh":"服装","vi":"Quần áo","th":"เสื้อผ้า","ru":"Одежда","id":"Pakaian"},
  {"ko":"공예품","en":"Crafts","ja":"工芸品","zh":"工艺品","vi":"Đồ thủ công","th":"งานฝีมือ","ru":"Ремесла","id":"Kerajinan Tangan"},
  {"ko":"수제도장","en":"Handmade Stamps","ja":"手作り印鑑","zh":"手工印章","vi":"Con dấu thủ công","th":"ตราประทับทำมือ","ru":"Печати ручной работы","id":"Stempel Buatan Tangan"},
  {"ko":"엔틱","en":"Antiques","ja":"アンティーク","zh":"古董","vi":"Đồ cổ","th":"ของเก่า","ru":"Антиквариат","id":"Barang Antik"},
  {"ko":"필방","en":"Calligraphy","ja":"書道","zh":"书法","vi":"Thư pháp","th":"พู่กันจีน","ru":"Каллиграфия","id":"Kaligrafi"},
  {"ko":"한복","en":"Hanbok","ja":"韓服","zh":"韩服","vi":"Hanbok","th":"ฮันบก","ru":"Ханбок","id":"Hanbok"},
  {"ko":"잡화","en":"Essentials","ja":"雑貨","zh":"杂货","vi":"Đồ tạp hóa","th":"ของใช้เบ็ดเตล็ด","ru":"Галантерея","id":"Barang Kebutuhan"},
  {"ko":"표구액자","en":"Mounting and Framing","ja":"作品の装丁と額装","zh":"装裱与框架","vi":"Đóng khung","th":"การเข้ากรอบ","ru":"Оформление в багет","id":"Pembingkaian"},
  {"ko":"고미술","en":"Antique Art","ja":"骨董品","zh":"古董艺术","vi":"Nghệ thuật cổ","th":"ศิลปะโบราณ","ru":"Античное искусство","id":"Seni Antik"},
  {"ko":"화랑","en":"Gallery","ja":"ギャラリー","zh":"画廊","vi":"Phòng trưng bày","th":"แกลเลอรี่","ru":"Галерея","id":"Galeri"},
  {"ko":"표구","en":"Calligraphy","ja":"書道","zh":"装裱","vi":"Thư pháp","th":"พู่กันจีน","ru":"Каллиграфия","id":"Kaligrafi"},
  {"ko":"전시관","en":"Exhibition Hall","ja":"展示館","zh":"展览馆","vi":"Phòng triển lãm","th":"ห้องนิทรรศการ","ru":"Выставочный зал","id":"Ruang Pameran"},
  {"ko":"역사유적지","en":"Historical Site","ja":"歴史的遺跡","zh":"历史遗址","vi":"Di tích lịch sử","th":"สถานที่ทางประวัติศาสตร์","ru":"Историческое место","id":"Situs Sejarah"},
  {"ko":"막걸리","en":"Makgeolli","ja":"マッコリ","zh":"24_米酒","vi":"Makgeolli","th":"มักกอลลี","ru":"Макколи","id":"Makgeolli"},
  {"ko":"전통주","en":"Traditional liquor","ja":"伝統酒","zh":"传统酒","vi":"Rượu truyền thống","th":"เหล้าแบบดั้งเดิม","ru":"Традиционный алкоголь","id":"Minuman Keras Tradisional"},
  {"ko":"기념품","en":"Souvenir","ja":"お土産","zh":"纪念品","vi":"Quà lưu niệm","th":"ของที่ระลึก","ru":"Сувениры","id":"Suvenir"},
  {"ko":"체험","en":"experience","ja":"体験","zh":"经验","vi":"Trải nghiệm","th":"ประสบการณ์","ru":"Опыт","id":"Pengalaman"},
  {"ko":"사진촬영","en":"photo shoot","ja":"写真撮影","zh":"照片拍摄","vi":"Chụp ảnh","th":"ถ่ายภาพ","ru":"Фотосессия","id":"Pemotretan"},
  {"ko":"K POP","en":"K POP","ja":"K POP","zh":"K POP","vi":"K POP","th":"K POP","ru":"K POP","id":"K POP"},
  {"ko":"다과","en":"Snacks","ja":"お茶菓子","zh":"茶点","vi":"Đồ ăn nhẹ","th":"ของว่าง","ru":"Закуски","id":"Camilan"},
];
