// AUTO-GENERATED by scripts/sync-sheet.mjs — do not edit by hand.
// Run `npm run sync:sheet` to refresh from the Google Sheet.
import type { LangText } from './types';

/** W006 제주공항 AI검색 categories, prefix stripped. */
export const AI_CATEGORIES_JEJU: LangText[] = [
  {"ko":"흑돼지","en":"black pig","ja":"黒豚","zh":"黑猪","vi":"lợn đen","th":"หมูดำ","ru":"черная свинья","id":"babi hitam"},
  {"ko":"해산물·회","en":"Seafood and Sashimi","ja":"シーフード・会","zh":"海鲜和刺身","vi":"Hải sản và Sashimi","th":"อาหารทะเลและซาชิมิ","ru":"Морепродукты и сашими","id":"Makanan Laut dan Sashimi"},
  {"ko":"갈치·고등어","en":"hairtail and mackerel","ja":"タバコ・サバ","zh":"带鱼和鲭鱼","vi":"cá đuôi dài và cá thu","th":"ปลาหางยาวและปลาแมคเคอเรล","ru":"сардина и скумбрия","id":"Ikan hairtail dan mackerel"},
  {"ko":"고기국수","en":"Meat noodles","ja":"肉麺","zh":"肉面","vi":"Mì thịt","th":"บะหมี่เนื้อ","ru":"Мясная лапша","id":"Mie daging"},
  {"ko":"제주 향토음식","en":"Jeju local food","ja":"済州の郷土料理","zh":"济州岛当地美食","vi":"Ẩm thực địa phương Jeju","th":"อาหารท้องถิ่นของเกาะเชจู","ru":"Местная еда на острове Чеджу","id":"Makanan lokal Jeju"},
  {"ko":"한식","en":"Korean food","ja":"韓国料理","zh":"韩国料理","vi":"Món ăn Hàn Quốc","th":"อาหารเกาหลี","ru":"корейская еда","id":"Makanan Korea"},
  {"ko":"한정식","en":"Korean set meal","ja":"限定式","zh":"韩式套餐","vi":"suất ăn kiểu Hàn Quốc","th":"ชุดอาหารเกาหลี","ru":"Корейский комплексный обед","id":"Paket makanan Korea"},
  {"ko":"호텔뷔페","en":"Hotel buffet","ja":"ホテルビュッフェ","zh":"酒店自助餐","vi":"Tiệc buffet khách sạn","th":"บุฟเฟ่ต์ของโรงแรม","ru":"Шведский стол в отеле","id":"Prasmanan hotel"},
  {"ko":"카페","en":"cafe","ja":"カフェ","zh":"咖啡店","vi":"quán cà phê","th":"คาเฟ่","ru":"кафе","id":"kafe"},
  {"ko":"제주특산품","en":"Jeju Specialties","ja":"済州特産品","zh":"济州特产","vi":"Đặc sản Jeju","th":"ของขึ้นชื่อเชจู","ru":"Деликатесы Чеджу","id":"Produk Khas Jeju"},
  {"ko":"전통차","en":"Traditional Tea","ja":"伝統茶","zh":"传统茶","vi":"Trà truyền thống","th":"ชาพื้นเมือง","ru":"Традиционный чай","id":"Teh Tradisional"},
  {"ko":"막걸리","en":"Makgeolli","ja":"マッコリ","zh":"马格利酒","vi":"Makgeolli","th":"มักกอลลี","ru":"Макколли","id":"Makgeolli"},
  {"ko":"전통주","en":"Traditional Liquor","ja":"伝統酒","zh":"传统酒","vi":"Rượu truyền thống","th":"สุราพื้นเมือง","ru":"Традиционные напитки","id":"Minuman Tradisional"},
  {"ko":"해녀 체험","en":"Haenyeo Experience","ja":"海女体験","zh":"海女体验","vi":"Trải nghiệm Haenyeo","th":"ประสบการณ์แฮนยอ","ru":"Опыт хэнё","id":"Pengalaman Haenyeo"},
  {"ko":"감귤 체험","en":"Tangerine Picking","ja":"みかん狩り","zh":"采摘柑橘","vi":"Hái quýt","th":"เก็บส้มเชจู","ru":"Сбор мандаринов","id":"Memetik Jeruk"},
  {"ko":"승마 체험","en":"Horse Riding","ja":"乗馬体験","zh":"骑马体验","vi":"Cưỡi ngựa","th":"ขี่ม้า","ru":"Верховая езда","id":"Berkuda"},
  {"ko":"레저·엑티비티","en":"Leisure & Activities","ja":"レジャー・アクティビティ","zh":"休闲与活动","vi":"Giải trí & Hoạt động","th":"17. กิจกรรมยามว่างและสันทนาการ","ru":"17. Досуг и развлечения","id":"Rekreasi & Aktivitas"},
  {"ko":"K-POP 체험","en":"K-POP Experience","ja":"K-POP体験","zh":"K-POP体验","vi":"Trải nghiệm K-POP 18 tuổi","th":"ประสบการณ์ K-POP 18 แบบ","ru":"K-POP Experience","id":"Pengalaman K-POP 18 tahun"},
  {"ko":"사진 촬영","en":"Photo Spots & Studios","ja":"写真スポット・写真館","zh":"拍照点·照相馆","vi":"Chụp ảnh","th":"จุดถ่ายรูป·สตูดิโอ","ru":"Фотосъёмка","id":"Spot Foto & Studio"},
  {"ko":"자연명소","en":"Natural Attractions","ja":"自然名所","zh":"自然景点","vi":"Danh thắng thiên nhiên","th":"แหล่งธรรมชาติ","ru":"Природные достопримечательности","id":"Objek Wisata Alam"},
  {"ko":"해변","en":"Beaches","ja":"ビーチ","zh":"海滩","vi":"Bãi biển","th":"ชายหาด","ru":"Пляжи","id":"Pantai"},
  {"ko":"섬 여행","en":"Island Trips","ja":"離島めぐり","zh":"离岛游","vi":"Du lịch đảo","th":"เที่ยวเกาะ","ru":"Поездки на острова","id":"Wisata Pulau"},
  {"ko":"오름·트래킹","en":"Oreum & Trekking","ja":"オルム・トレッキング","zh":"Oreum 火山丘·徒步","vi":"Oreum & Trekking","th":"โอรึม·เดินป่า","ru":"Орым и треккинг","id":"Oreum & Trekking"},
  {"ko":"역사유적지","en":"Historic Sites","ja":"史跡","zh":"历史遗址","vi":"Di tích lịch sử","th":"โบราณสถาน","ru":"Исторические места","id":"Situs Bersejarah"},
  {"ko":"제주 기념품","en":"Jeju Souvenirs","ja":"済州のお土産","zh":"济州纪念品","vi":"Quà lưu niệm Jeju","th":"ของที่ระลึกเชจู","ru":"Сувениры Чеджу","id":"Suvenir Jeju"},
  {"ko":"공예품","en":"Crafts","ja":"工芸品","zh":"手工艺品","vi":"Đồ thủ công","th":"งานหัตถกรรม","ru":"Ремесленные изделия","id":"Kerajinan Tangan"},
  {"ko":"전통시장","en":"Traditional Markets","ja":"伝統市場","zh":"传统市场","vi":"Chợ truyền thống","th":"ตลาดดั้งเดิม","ru":"Традиционные рынки","id":"Pasar Tradisional"},
  {"ko":"전시관·문화공간","en":"Museums & Culture","ja":"展示館・文化施設","zh":"展馆·文化空间","vi":"Bảo tàng & Không gian văn hóa","th":"พิพิธภัณฑ์·พื้นที่วัฒนธรรม","ru":"Музеи и культурные пространства","id":"Museum & Ruang Budaya"},
  {"ko":"로컬샵","en":"Local Shops","ja":"ローカルショップ","zh":"本地小店","vi":"Cửa hàng địa phương","th":"ร้านท้องถิ่น","ru":"Локальные магазины","id":"Toko Lokal"},
  {"ko":"기타","en":"Others","ja":"その他","zh":"其他","vi":"Khác","th":"อื่นๆ","ru":"Прочее","id":"Lainnya"},
];
