// AUTO-GENERATED by scripts/sync-sheet.mjs — do not edit by hand.
// Run `npm run sync:sheet` to refresh from the Google Sheet.
import type { LangText } from './types';

/** W005 화성휴게소 모하지(AI검색) 즐길거리 categories, prefix stripped. */
export const AI_CATEGORIES_HWASEONG: LangText[] = [
  {"ko":"카페 및 베이커리","en":"Café & Bakery","ja":"カフェ・ベーカリー","zh":"咖啡店与烘焙店"},
  {"ko":"동남아","en":"Southeast Asian Cuisine","ja":"東南アジア料理","zh":"东南亚美食"},
  {"ko":"차이나","en":"Chinese Cuisine","ja":"中華料理","zh":"中餐"},
  {"ko":"중식","en":"Chinese Food (General)","ja":"中華フード","zh":"中式餐饮"},
  {"ko":"한식","en":"Korean Cuisine","ja":"韓国料理","zh":"韩餐"},
  {"ko":"분식","en":"Korean Street Food","ja":"韓国屋台料理","zh":"韩式小吃"},
  {"ko":"야채/과일","en":"Vegetables/Fruits","ja":"果物/野菜","zh":"水果/蔬菜"},
  {"ko":"채소/농산","en":"Vegetables/Agricultural","ja":"野菜/農産物","zh":"蔬菜/农产"},
  {"ko":"인삼/약재","en":"Ginseng/Herbs","ja":"高麗人参/薬材","zh":"人参/药材"},
  {"ko":"찌개류/국류","en":"Stews/Soups","ja":"チゲ/スープ","zh":"炖菜/汤"},
  {"ko":"족발/만두","en":"Pig’s Trotters/Dumplings","ja":"豚足/餃子","zh":"猪蹄/饺子"},
  {"ko":"치킨/강정","en":"Chicken/Fried Chicken","ja":"チキン/カンジョン","zh":"炸鸡/酥鸡"},
  {"ko":"떡/두부","en":"Rice Cakes/Tofu","ja":"餅/豆腐","zh":"年糕/豆腐"},
  {"ko":"기름/방앗간","en":"Oil/Mill","ja":"油/搾油","zh":"油/榨油"},
  {"ko":"축산/정육","en":"Livestock/Butchery","ja":"畜産/精肉","zh":"畜产/肉铺"},
  {"ko":"수산/건어물","en":"Seafood","ja":"水産/乾物","zh":"水产/干货"},
  {"ko":"가구","en":"Furniture","ja":"家具","zh":"家具"},
  {"ko":"뷰티/미용","en":"Beauty","ja":"美容","zh":"美容"},
  {"ko":"건강","en":"Health","ja":"健康","zh":"健康"},
  {"ko":"의류","en":"Clothing","ja":"衣類","zh":"服装"},
  {"ko":"신발","en":"Shoes","ja":"靴","zh":"鞋"},
  {"ko":"패션잡화","en":"Accessories","ja":"服飾雑貨","zh":"配饰"},
  {"ko":"생활용품","en":"Household","ja":"生活用品","zh":"生活用品"},
  {"ko":"문구","en":"Stationery","ja":"文具","zh":"文具"},
  {"ko":"인테리어/수리","en":"Interior/Repair","ja":"インテリア/修理","zh":"家居/维修"},
];
