// AUTO-GENERATED by scripts/sync-sheet.mjs — do not edit by hand.
// Run `npm run sync:sheet` to refresh from the Google Sheet.
import type { LangText } from './types';

/** W005 화성휴게소 모하지(AI검색) 즐길거리 categories, prefix stripped. */
export const AI_CATEGORIES_HWASEONG: LangText[] = [
  {"ko":"카페 및 베이커리","en":"Café & Bakery","ja":"カフェ・ベーカリー","zh":"咖啡店与烘焙店","vi":"Quán cà phê & Tiệm bánh","th":"คาเฟ่และเบเกอรี่","ru":"Кафе и пекарня","id":"Kafe & Toko Roti"},
  {"ko":"동남아","en":"Southeast Asian Cuisine","ja":"東南アジア料理","zh":"东南亚美食","vi":"Ẩm thực Đông Nam Á","th":"อาหารเอเชียตะวันออกเฉียงใต้","ru":"Кухня Юго-Восточной Азии","id":"Masakan Asia Tenggara"},
  {"ko":"차이나","en":"Chinese Cuisine","ja":"中華料理","zh":"中餐","vi":"Ẩm thực Trung Hoa","th":"อาหารจีน","ru":"Китайская кухня","id":"Masakan Cina"},
  {"ko":"중식","en":"Chinese Food (General)","ja":"中華フード","zh":"中式餐饮","vi":"Món Trung Quốc","th":"อาหารจีน (ทั่วไป)","ru":"Китайская еда","id":"Makanan Cina"},
  {"ko":"한식","en":"Korean Cuisine","ja":"韓国料理","zh":"韩餐","vi":"Ẩm thực Hàn Quốc","th":"อาหารเกาหลี","ru":"Корейская кухня","id":"Masakan Korea"},
  {"ko":"분식","en":"Korean Street Food","ja":"韓国屋台料理","zh":"韩式小吃","vi":"Ăn vặt Hàn Quốc","th":"สตรีทฟู้ดเกาหลี","ru":"Корейская уличная еда","id":"Jajanan Korea"},
  {"ko":"야채/과일","en":"Vegetables/Fruits","ja":"果物/野菜","zh":"水果/蔬菜","vi":"Rau củ/Trái cây","th":"ผัก/ผลไม้","ru":"Овощи/Фрукты","id":"Sayuran/Buah"},
  {"ko":"채소/농산","en":"Vegetables/Agricultural","ja":"野菜/農産物","zh":"蔬菜/农产","vi":"Rau củ/Nông sản","th":"ผัก/สินค้าเกษตร","ru":"Овощи/Сельхозпродукция","id":"Sayuran/Hasil Pertanian"},
  {"ko":"인삼/약재","en":"Ginseng/Herbs","ja":"高麗人参/薬材","zh":"人参/药材","vi":"Nhân sâm/Dược liệu","th":"โสม/สมุนไพร","ru":"Женьшень/Травы","id":"Ginseng/Obat Herbal"},
  {"ko":"찌개류/국류","en":"Stews/Soups","ja":"チゲ/スープ","zh":"炖菜/汤","vi":"Món hầm/Súp","th":"สตูว์/ซุป","ru":"Рагу/Супы","id":"Rebusan/Sup"},
  {"ko":"족발/만두","en":"Pig’s Trotters/Dumplings","ja":"豚足/餃子","zh":"猪蹄/饺子","vi":"Chân giò/Bánh bao","th":"ขาหมู/เกี๊ยว","ru":"Свиные ножки/Пельмени","id":"Kaki Babi/Pangsit"},
  {"ko":"치킨/강정","en":"Chicken/Fried Chicken","ja":"チキン/カンジョン","zh":"炸鸡/酥鸡","vi":"Gà/Gà rán","th":"ไก่/ไก่ทอด","ru":"Курица/Жареная курица","id":"Ayam/Ayam Goreng"},
  {"ko":"떡/두부","en":"Rice Cakes/Tofu","ja":"餅/豆腐","zh":"年糕/豆腐","vi":"Bánh gạo/Đậu phụ","th":"เค้กข้าว/เต้าหู้","ru":"Рисовые пирожки/Тофу","id":"Kue Beras/Tahu"},
  {"ko":"기름/방앗간","en":"Oil/Mill","ja":"油/搾油","zh":"油/榨油","vi":"Dầu/Xưởng ép dầu","th":"น้ำมัน/โรงสี","ru":"Масло/Мельница","id":"Minyak/Penggilingan"},
  {"ko":"축산/정육","en":"Livestock/Butchery","ja":"畜産/精肉","zh":"畜产/肉铺","vi":"Chăn nuôi/Cửa hàng thịt","th":"ปศุสัตว์/ร้านขายเนื้อ","ru":"Животноводство/Мясная лавка","id":"Peternakan/Toko Daging"},
  {"ko":"수산/건어물","en":"Seafood","ja":"水産/乾物","zh":"水产/干货","vi":"Hải sản/Đồ khô","th":"อาหารทะเล/อาหารแห้ง","ru":"Морепродукты/Сушеные продукты","id":"Makanan Laut/Makanan Kering"},
  {"ko":"가구","en":"Furniture","ja":"家具","zh":"家具","vi":"Nội thất","th":"เฟอร์นิเจอร์","ru":"Мебель","id":"Furnitur"},
  {"ko":"뷰티/미용","en":"Beauty","ja":"美容","zh":"美容","vi":"Làm đẹp","th":"ความงาม","ru":"Красота","id":"Kecantikan"},
  {"ko":"건강","en":"Health","ja":"健康","zh":"健康","vi":"Sức khỏe","th":"สุขภาพ","ru":"Здоровье","id":"Kesehatan"},
  {"ko":"의류","en":"Clothing","ja":"衣類","zh":"服装","vi":"Quần áo","th":"เสื้อผ้า","ru":"Одежда","id":"Pakaian"},
  {"ko":"신발","en":"Shoes","ja":"靴","zh":"鞋","vi":"Giày dép","th":"รองเท้า","ru":"Обувь","id":"Sepatu"},
  {"ko":"패션잡화","en":"Accessories","ja":"服飾雑貨","zh":"配饰","vi":"Phụ kiện","th":"เครื่องประดับ","ru":"Аксессуары","id":"Aksesoris"},
  {"ko":"생활용품","en":"Household","ja":"生活用品","zh":"生活用品","vi":"Đồ gia dụng","th":"ของใช้ในบ้าน","ru":"Товары для дома","id":"Perlengkapan Rumah Tangga"},
  {"ko":"문구","en":"Stationery","ja":"文具","zh":"文具","vi":"Văn phòng phẩm","th":"เครื่องเขียน","ru":"Канцтовары","id":"Alat Tulis"},
  {"ko":"인테리어/수리","en":"Interior/Repair","ja":"インテリア/修理","zh":"家居/维修","vi":"Nội thất/Sửa chữa","th":"ตกแต่งภายใน/ซ่อมแซม","ru":"Интерьер/Ремонт","id":"Interior/Perbaikan"},
];
