// AUTO-GENERATED by scripts/sync-sheet.mjs — do not edit by hand.
// Run `npm run sync:sheet` to refresh from the Google Sheet.
import type { LangText } from './types';

/** '인사' 뭐하지 (AI검색) — 즐길거리 categories, prefix stripped. */
export const AI_CATEGORIES: LangText[] = [
  {"ko":"코리안바베큐","en":"Korean BBQ","ja":"韓国のバーベキュー","zh":"韩国烧烤"},
  {"ko":"한식","en":"Korean food","ja":"韓国料理","zh":"韩国菜"},
  {"ko":"한정식","en":"Course meal","ja":"韓定食","zh":"韩定食"},
  {"ko":"분식","en":"Street Food","ja":"韓国の軽食","zh":"韩国小吃"},
  {"ko":"사찰음식","en":"Temple Food","ja":"査察料理","zh":"寺庙食物"},
  {"ko":"채식/비건","en":"Vegetarian","ja":"ベジタリアン/ビーガン","zh":"素食/纯素食"},
  {"ko":"아시안","en":"Asian","ja":"アジア","zh":"亚洲人"},
  {"ko":"중식","en":"Chinese food","ja":"昼食","zh":"午餐"},
  {"ko":"전통차","en":"Traditional Tea","ja":"伝統的な車","zh":"传统茶"},
  {"ko":"카페","en":"Cafe","ja":"カフェ","zh":"咖啡馆"},
  {"ko":"의류","en":"Clothing","ja":"衣類","zh":"服装"},
  {"ko":"공예품","en":"Crafts","ja":"工芸品","zh":"工艺品"},
  {"ko":"수제도장","en":"Handmade Stamps","ja":"手作り印鑑","zh":"手工印章"},
  {"ko":"엔틱","en":"Antiques","ja":"アンティーク","zh":"古董"},
  {"ko":"필방","en":"Calligraphy","ja":"書道","zh":"书法"},
  {"ko":"한복","en":"Hanbok","ja":"韓服","zh":"韩服"},
  {"ko":"잡화","en":"Essentials","ja":"雑貨","zh":"杂货"},
  {"ko":"표구액자","en":"Mounting and Framing","ja":"作品の装丁と額装","zh":"装裱与框架"},
  {"ko":"고미술","en":"Antique Art","ja":"骨董品","zh":"古董艺术"},
  {"ko":"화랑","en":"Gallery","ja":"ギャラリー","zh":"画廊"},
  {"ko":"표구","en":"Calligraphy","ja":"書道","zh":"装裱"},
  {"ko":"전시관","en":"Exhibition Hall","ja":"展示館","zh":"展览馆"},
  {"ko":"역사유적지","en":"Historical Site","ja":"歴史的遺跡","zh":"历史遗址"},
  {"ko":"막걸리","en":"Makgeolli","ja":"マッコリ","zh":"24_米酒"},
  {"ko":"전통주","en":"Traditional liquor","ja":"伝統酒","zh":"传统酒"},
  {"ko":"기념품","en":"Souvenir","ja":"お土産","zh":"纪念品"},
  {"ko":"체험","en":"experience","ja":"体験","zh":"经验"},
  {"ko":"사진촬영","en":"photo shoot","ja":"写真撮影","zh":"照片拍摄"},
  {"ko":"K POP","en":"K POP","ja":"K POP","zh":"K POP"},
  {"ko":"다과","en":"Snacks","ja":"お茶菓子","zh":"茶点"},
];
