// AUTO-GENERATED by scripts/sync-sheet.mjs — do not edit by hand.
// Run `npm run sync:sheet` to refresh from the Google Sheet.
import type { LangText } from './types';

/** W006 제주공항 AI검색 categories, prefix stripped. */
export const AI_CATEGORIES_JEJU: LangText[] = [
  {"ko":"흑돼지","en":"black pig","ja":"黒豚","zh":"黑猪","vi":"lợn đen","th":"หมูดำ","ru":"черная свинья","id":"babi hitam"},
  {"ko":"해산물·회","en":"Seafood and Sashimi","ja":"シーフード・会","zh":"海鲜和刺身","vi":"Hải sản và Sashimi","th":"อาหารทะเลและซาชิมิ","ru":"Морепродукты и сашими","id":"Makanan Laut dan Sashimi"},
  {"ko":"갈치·고등어","en":"hairtail and mackerel","ja":"タバコ・サバ","zh":"带鱼和鲭鱼","vi":"cá đuôi dài và cá thu","th":"ปลาหางยาวและปลาแมคเคอเรล","ru":"сардина и скумбрия","id":"Ikan hairtail dan mackerel"},
  {"ko":"고기국수","en":"Meat noodles","ja":"肉麺","zh":"肉面","vi":"Mì thịt","th":"บะหมี่เนื้อ","ru":"Мясная лапша","id":"Mie daging"},
  {"ko":"제주 향토음식","en":"Jeju local food","ja":"済州の郷土料理","zh":"济州岛当地美食","vi":"Ẩm thực địa phương Jeju","th":"อาหารท้องถิ่นของเกาะเชจู","ru":"Местная еда на острове Чеджу","id":"Makanan lokal Jeju"},
  {"ko":"한식","en":"Korean food","ja":"韓国料理","zh":"韩国料理","vi":"Món ăn Hàn Quốc","th":"อาหารเกาหลี","ru":"корейская еда","id":"Makanan Korea"},
  {"ko":"한정식","en":"Korean set meal","ja":"限定式","zh":"韩式套餐","vi":"suất ăn kiểu Hàn Quốc","th":"ชุดอาหารเกาหลี","ru":"Корейский комплексный обед","id":"Paket makanan Korea"},
  {"ko":"호텔뷔페","en":"Hotel buffet","ja":"ホテルビュッフェ","zh":"酒店自助餐","vi":"Tiệc buffet khách sạn","th":"บุฟเฟ่ต์ของโรงแรม","ru":"Шведский стол в отеле","id":"Prasmanan hotel"},
  {"ko":"카페","en":"cafe","ja":"カフェ","zh":"咖啡店","vi":"quán cà phê","th":"คาเฟ่","ru":"кафе","id":"kafe"},
  {"ko":"제주특산품","en":"Jeju Specialty Products","ja":"済州特産品","zh":"济州岛特产","vi":"Sản phẩm đặc sản Jeju","th":"10 ผลิตภัณฑ์พิเศษจากเกาะเชจู","ru":"10. Специализированная продукция острова Чеджу","id":"Produk Khas Jeju"},
  {"ko":"전통차","en":"Traditional Tea","ja":"伝統的な車","zh":"传统茶","vi":"Trà truyền thống","th":"11. ชาแบบดั้งเดิม","ru":"11. Традиционный чай","id":"Teh Tradisional"},
  {"ko":"막걸리","en":"Makgeolli","ja":"マッコリ","zh":"马格利酒","vi":"Makgeolli","th":"มักเกอลี","ru":"Макгеолли","id":"Makgeolli"},
  {"ko":"전통주","en":"Traditional Liquor","ja":"伝統株","zh":"传统酒","vi":"Rượu truyền thống","th":"13.สุราแบบดั้งเดิม","ru":"13. Традиционный алкогольный напиток","id":"Minuman Keras Tradisional"},
  {"ko":"해녀 체험","en":"Haenyeo Experience","ja":"海女体験","zh":"海女经历","vi":"Trải nghiệm Haenyeo","th":"ประสบการณ์ 14-Haenyeo","ru":"Опыт Хэнё","id":"Pengalaman Haenyeo"},
  {"ko":"감귤 체험","en":"Tangerine Experience","ja":"柑橘系の体験","zh":"橘子体验","vi":"Trải nghiệm 15 quả quýt","th":"ประสบการณ์ส้มแมนดาริน 15 ชนิด","ru":"Мандариновый опыт","id":"Pengalaman Jeruk Mandarin 15-"},
  {"ko":"승마 체험","en":"Horseback Riding Experience","ja":"乗馬体験","zh":"16次骑马体验","vi":"Trải nghiệm cưỡi ngựa 16 ngày","th":"ประสบการณ์ขี่ม้า 16 ครั้ง","ru":"Программа верховой езды на 16 лошадях","id":"Pengalaman Berkuda 16 Hari"},
  {"ko":"레저·엑티비티","en":"Leisure & Activities","ja":"レジャー・アクティビティ","zh":"休闲与活动","vi":"Giải trí & Hoạt động","th":"17. กิจกรรมยามว่างและสันทนาการ","ru":"17. Досуг и развлечения","id":"Rekreasi & Aktivitas"},
  {"ko":"K-POP 체험","en":"K-POP Experience","ja":"K-POP体験","zh":"K-POP体验","vi":"Trải nghiệm K-POP 18 tuổi","th":"ประสบการณ์ K-POP 18 แบบ","ru":"K-POP Experience","id":"Pengalaman K-POP 18 tahun"},
  {"ko":"사진 촬영","en":"Photography","ja":"写真撮影","zh":"摄影","vi":"Nhiếp ảnh","th":"19. การถ่ายภาพ","ru":"19. Фотография","id":"Fotografi"},
  {"ko":"자연명소","en":"Natural Attractions","ja":"自然スポット","zh":"20. 自然景点","vi":"Điểm tham quan tự nhiên","th":"20 สถานที่ท่องเที่ยวทางธรรมชาติ","ru":"20 природных достопримечательностей","id":"20 Objek Wisata Alam"},
  {"ko":"해변","en":"Beach","ja":"ビーチ","zh":"海滩","vi":"Bãi biển số 21","th":"บีช","ru":"Бич","id":"Pantai 21"},
  {"ko":"섬 여행","en":"Island Trip","ja":"島旅行","zh":"22岛之旅","vi":"Chuyến đi 22 hòn đảo","th":"ทริปเที่ยว 22 เกาะ","ru":"Путешествие по 22 островам","id":"Perjalanan ke 22 Pulau"},
  {"ko":"오름·트래킹","en":"Oreum·Trekking","ja":"オルム・トラッキング","zh":"奥雷姆·徒步旅行","vi":"Oreum·Trekking","th":"โอเรียม·การเดินป่า","ru":"Ореум·Трекинг","id":"Oreum·Trekking"},
  {"ko":"역사유적지","en":"Historical Sites","ja":"歴史遺跡","zh":"24处历史遗址","vi":"24 Di tích Lịch sử","th":"สถานที่ทางประวัติศาสตร์","ru":"24 исторических места","id":"24 Situs Bersejarah"},
  {"ko":"제주 기념품","en":"Jeju Souvenirs","ja":"済州のお土産","zh":"济州岛纪念品","vi":"25 món quà lưu niệm Jeju","th":"ของที่ระลึกจากเกาะเชจู 25 ชิ้น","ru":"25 сувениров с острова Чеджу","id":"25 Suvenir Jeju"},
  {"ko":"공예품","en":"Crafts","ja":"工芸品","zh":"工艺品","vi":"Thủ công mỹ nghệ","th":"งานฝีมือ","ru":"Ремесла","id":"26 Kerajinan Tangan"},
  {"ko":"전통시장","en":"Traditional Market","ja":"伝統市場","zh":"传统市场","vi":"Chợ truyền thống","th":"ตลาดแบบดั้งเดิม","ru":"27. Традиционный рынок","id":"Pasar Tradisional"},
  {"ko":"전시관·문화공간","en":"Exhibition Halls · Cultural Spaces","ja":"展示館・文化空間","zh":"展览馆·文化空间","vi":"28 phòng triển lãm · Không gian văn hóa","th":"ห้องจัดแสดงนิทรรศการ · พื้นที่ทางวัฒนธรรม","ru":"28 выставочных залов · Культурные пространства","id":"Aula Pameran · Ruang Budaya"},
  {"ko":"로컬샵","en":"Local Shop","ja":"ローカルショップ","zh":"本地商店","vi":"Cửa hàng địa phương","th":"ร้านค้าท้องถิ่น","ru":"Местный магазин","id":"Toko Lokal"},
  {"ko":"기타","en":"Others","ja":"その他","zh":"其他","vi":"Khác","th":"อื่นๆ","ru":"Другие","id":"30 Lainnya"},
];
