// AUTO-GENERATED by scripts/sync-sheet.mjs — do not edit by hand.
// Run `npm run sync:sheet` to refresh from the Google Sheet.
import type { LangText } from './types';

/** W008 세계자연유산본부 (JEJU_HERITAGE): the Localization_Jeju keys whose venue
 *  pick differs from W006's — i.e. the 유산-mascot rows. Overlaid on
 *  LOCALIZATION_JEJU by loc.ts; mirrors the runtime split in
 *  LocalizationSyncParser.VENUE_MASCOTS. */
export const LOCALIZATION_JEJU_HERITAGE_OVERRIDES: Record<string, LangText> = {
  "NoticeContent": {"ko":"제주도의 마스코트<b>'YUSAN'이\n박술녀 한복을</b> 입고 나와요\n여러분도 체험할 수 있도록 \n할게요 <b>한복을 입어보세요~</b>","en":"YUSAN will appear in a brand-new hanboks  by Park Sulnyeo!\nGet ready to enjoy the hanbok experience with all-new designs.","ja":"YUSANはパク・スルニョによる全く新しい韓服（ハンボク）で登場します！ 新しいデザインの韓服体験をお楽しみに！","zh":"YUSAN\n将身着朴洙烈设计的全新韩服亮相！\n敬请期待全新设计的韩服体验！","vi":"Linh vật Insadong 'YUSAN' mặc Hanbok Bak Sul-nyeo xuất hiện! Chúng tôi sẽ giúp các bạn cùng trải nghiệm. Hãy thử Hanbok nhé~","th":"มาสคอตอินซาดง 'YUSAN' สวมฮันบกพัคซุลนยอมาแล้ว! เราจะทำให้ทุกคนได้สัมผัสประสบการณ์นี้ มาลองสวมชุดฮันบกกัน~","ru":"YUSAN появится в совершенно новых ханбоках от Пак Суль Нё!\nПриготовьтесь насладиться примеркой ханбоков с совершенно новым дизайном.","id":"Maskot Insadong 'YUSAN' tampil pakai Hanbok Bak Sul-nyeo! Kami siapkan agar kalian juga bisa mencobanya. Ayo coba Hanbok~"},
  "MainButton_Greeting": {"ko":"안녕 '유산'","en":"Hello 'YUSAN'","ja":"こんにちは 'YUSAN'","zh":"你好 'YUSAN'","vi":"Chào 'YUSAN'","th":"สวัสดี 'YUSAN'","ru":"Привет, 'YUSAN'","id":"Halo 'YUSAN'"},
  "MainButton_ToHelp": {"ko":"도와줘'유산'","en":"Help","ja":"ヘルプとサービスです","zh":"请帮忙","vi":"Giúp với 'YUSAN'","th":"ช่วยด้วย 'YUSAN'","ru":"Помощь","id":"Tolong 'YUSAN'"},
  "SubButton_Greeting": {"ko":"유산' 소개","en":"","ja":"","zh":""},
  "Greeting_Introduce": {"ko":"* 안녕하세요! 마스코트 '유산'를 소개할게요!","en":"","ja":"","zh":""},
  "Greeting_Category1": {"ko":"유산' 소개","en":"","ja":"","zh":""},
  "Greeting_Category2": {"ko":"유산' 취미생활","en":"","ja":"","zh":""},
  "Greeting_Category3": {"ko":"유산' 건강습관","en":"","ja":"","zh":""},
  "Greeting_NameContent": {"ko":"유산","en":"Yusan","ja":"インサ","zh":"英莎","vi":"INSA","th":"INSA","ru":"INSA","id":"INSA"},
  "Photo_SelectTogether": {"ko":"사진촬영 (with '유산')","en":"With ‘Yusan’","ja":"","zh":""},
};
