/**
 * Strings for the 제주 motion games, in the kiosk's eight languages.
 *
 * Separate from `gameText.ts` for the same reason the motion games are a
 * separate folder: these screens are read from two metres away by someone with
 * their hands in the air, so the copy is written to a different brief — three
 * words, an emoji that carries the meaning on its own, and nothing that needs
 * to be read twice. Keeping the two tables apart stops that voice leaking into
 * the touch games and vice versa.
 *
 * ── Every one of these has to work as a GLANCE ────────────────────────
 * A visitor mid-game is not reading. The coaching lines especially (`stepInFront`,
 * `backIntoView`, `onePlayer`) are paired with a large glyph in the component,
 * and if the glyph alone does not carry it the line is wrong.
 */
import type { Lang } from '@renderer/lib/i18n';

type Str = Partial<Record<Lang, string>>;

export const MOTION = {
  // ── Cards ─────────────────────────────────────────────────────────────
  catchName: {
    ko: '몸으로 감귤 받기',
    en: 'Body Tangerine Catch',
    ja: '体でみかんキャッチ',
    zh: '用身体接柑橘',
    vi: 'Hứng Quýt Bằng Cơ Thể',
    th: 'รับส้มด้วยร่างกาย',
    ru: 'Лови мандарины телом',
    id: 'Tangkap Jeruk dengan Tubuh',
  } as Str,
  catchDesc: {
    ko: '몸을 움직여 감귤을 받으세요!',
    en: 'Move your body to catch the tangerines!',
    ja: '体を左右に動かしてみかんをキャッチ！',
    zh: '左右移动身体接住柑橘！',
    vi: 'Di chuyển cơ thể để hứng quýt!',
    th: 'ขยับตัวซ้ายขวาเพื่อรับส้ม!',
    ru: 'Двигайтесь и ловите мандарины!',
    id: 'Gerakkan tubuh untuk menangkap jeruk!',
  } as Str,
  poseName: {
    ko: '제주 포즈 챌린지',
    en: 'Pose Challenge',
    ja: '済州ポーズチャレンジ',
    zh: '济州姿势挑战',
    vi: 'Thử Thách Tạo Dáng',
    th: 'ท้าโพสท่าเชจู',
    ru: 'Позы Чеджу',
    id: 'Tantangan Pose Jeju',
  } as Str,
  poseDesc: {
    ko: '제주 포즈를 따라 해보세요!',
    en: 'Copy the Jeju poses!',
    ja: '済州のポーズを真似しよう！',
    zh: '模仿济州姿势！',
    vi: 'Bắt chước các tư thế Jeju!',
    th: 'ทำท่าตามแบบเชจู!',
    ru: 'Повторите позы Чеджу!',
    id: 'Tirukan pose Jeju!',
  } as Str,
  dodgeName: {
    ko: '화산석 피하기',
    en: 'Dodge Rocks',
    ja: '火山石よけ',
    zh: '躲避火山石',
    vi: 'Né Đá Núi Lửa',
    th: 'หลบหินภูเขาไฟ',
    ru: 'Уклонись от камней',
    id: 'Hindari Batu Vulkanik',
  } as Str,
  dodgeDesc: {
    ko: '몸을 움직여 화산석을 피하세요!',
    en: 'Move your body and avoid the rocks!',
    ja: '体を動かして火山石をよけよう！',
    zh: '移动身体躲开火山石！',
    vi: 'Di chuyển để né đá núi lửa!',
    th: 'ขยับตัวหลบหินภูเขาไฟ!',
    ru: 'Двигайтесь и уклоняйтесь от камней!',
    id: 'Bergeraklah menghindari batu!',
  } as Str,

  // ── Calibration / coaching ────────────────────────────────────────────
  stepInFront: {
    ko: '화면 앞에 서주세요',
    en: 'Step in front of the screen',
    ja: '画面の前に立ってください',
    zh: '请站到屏幕前',
    vi: 'Hãy đứng trước màn hình',
    th: 'กรุณายืนหน้าจอ',
    ru: 'Встаньте перед экраном',
    id: 'Berdirilah di depan layar',
  } as Str,
  ready: {
    ko: '준비 완료!',
    en: 'READY!',
    ja: '準備完了！',
    zh: '准备好了！',
    vi: 'SẴN SÀNG!',
    th: 'พร้อมแล้ว!',
    ru: 'ГОТОВО!',
    id: 'SIAP!',
  } as Str,
  backIntoView: {
    ko: '화면 안으로 들어와 주세요',
    en: 'Move back into view',
    ja: '画面の中に戻ってください',
    zh: '请回到画面中',
    vi: 'Hãy vào lại khung hình',
    th: 'กลับเข้ามาในจอด้วย',
    ru: 'Вернитесь в кадр',
    id: 'Kembali ke dalam layar',
  } as Str,
  moveIntoArea: {
    ko: '게임 영역 안으로 이동해 주세요',
    en: 'Move back into the game area',
    ja: 'ゲームエリアに戻ってください',
    zh: '请回到游戏区域',
    vi: 'Hãy vào lại khu vực chơi',
    th: 'กลับเข้าพื้นที่เล่นด้วย',
    ru: 'Вернитесь в игровую зону',
    id: 'Kembali ke area permainan',
  } as Str,
  onePlayer: {
    ko: '한 명만 플레이해 주세요',
    en: 'One player please',
    ja: '一人でプレイしてください',
    zh: '请一人游玩',
    vi: 'Chỉ một người chơi',
    th: 'ขอผู้เล่นคนเดียว',
    ru: 'Пожалуйста, играйте по одному',
    id: 'Satu pemain saja',
  } as Str,
  /** The line that answers "I AM standing here" — they were too close. */
  stepBack: {
    ko: '조금 뒤로 물러나 주세요',
    en: 'Step back a little',
    ja: '少し後ろに下がってください',
    zh: '请稍微后退一点',
    vi: 'Hãy lùi lại một chút',
    th: 'ถอยหลังอีกนิด',
    ru: 'Отойдите немного назад',
    id: 'Mundur sedikit',
  } as Str,
  stepCloser: {
    ko: '조금 앞으로 와주세요',
    en: 'Come a little closer',
    ja: '少し前に来てください',
    zh: '请稍微靠近一点',
    vi: 'Hãy lại gần hơn một chút',
    th: 'เข้ามาใกล้อีกนิด',
    ru: 'Подойдите чуть ближе',
    id: 'Mendekat sedikit',
  } as Str,
  /** Shown under the silhouette so the visitor knows where to stand. */
  standHere: {
    ko: '전신이 다 보이지 않아도 괜찮아요',
    en: "Your whole body doesn't need to fit",
    ja: '全身が入らなくても大丈夫です',
    zh: '不用露出全身也可以',
    vi: 'Không cần lộ toàn thân',
    th: 'ไม่ต้องเห็นทั้งตัวก็ได้',
    ru: 'Всё тело показывать не нужно',
    id: 'Tidak perlu seluruh tubuh terlihat',
  } as Str,
  moveLeftRight: {
    ko: '좌우로 움직이세요',
    en: 'Move left and right',
    ja: '左右に動かしてください',
    zh: '左右移动',
    vi: 'Di chuyển sang trái phải',
    th: 'ขยับซ้ายขวา',
    ru: 'Двигайтесь влево и вправо',
    id: 'Bergerak ke kiri dan kanan',
  } as Str,
  cameraOff: {
    ko: '카메라를 사용할 수 없어요',
    en: 'The camera is unavailable',
    ja: 'カメラを使用できません',
    zh: '摄像头无法使用',
    vi: 'Không dùng được camera',
    th: 'ใช้กล้องไม่ได้',
    ru: 'Камера недоступна',
    id: 'Kamera tidak tersedia',
  } as Str,
  cameraOffSub: {
    ko: '터치로 즐기는 다른 게임을 해보세요',
    en: 'Try one of the touch games instead',
    ja: 'タッチで遊べる他のゲームをどうぞ',
    zh: '试试其他触屏游戏吧',
    vi: 'Hãy thử các trò chơi cảm ứng khác',
    th: 'ลองเกมแบบสัมผัสอื่นดูสิ',
    ru: 'Попробуйте игры с сенсорным экраном',
    id: 'Coba gim sentuh lainnya',
  } as Str,
  /** Monitor 2 has no touch — this points the visitor at the screen that does. */
  useTouchScreen: {
    ko: '아래 화면에서 조작해 주세요',
    en: 'Use the screen below',
    ja: '下の画面で操作してください',
    zh: '请使用下方屏幕操作',
    vi: 'Hãy dùng màn hình bên dưới',
    th: 'ใช้หน้าจอด้านล่าง',
    ru: 'Используйте нижний экран',
    id: 'Gunakan layar di bawah',
  } as Str,
  starting: {
    ko: '카메라를 준비하고 있어요…',
    en: 'Getting the camera ready…',
    ja: 'カメラを準備しています…',
    zh: '正在准备摄像头…',
    vi: 'Đang chuẩn bị camera…',
    th: 'กำลังเตรียมกล้อง…',
    ru: 'Готовим камеру…',
    id: 'Menyiapkan kamera…',
  } as Str,

  /** The remote's headline: the game is on the OTHER screen. */
  lookAtBigScreen: {
    ko: '위쪽 큰 화면을 봐주세요!',
    en: 'Look at the big screen above!',
    ja: '上の大きな画面を見てください！',
    zh: '请看上方大屏幕！',
    vi: 'Hãy nhìn màn hình lớn phía trên!',
    th: 'ดูที่จอใหญ่ด้านบน!',
    ru: 'Смотрите на большой экран сверху!',
    id: 'Lihat layar besar di atas!',
  } as Str,
  /** The one control available while a motion game runs. */
  stopGame: {
    ko: '그만하기',
    en: 'Stop',
    ja: 'やめる',
    zh: '结束',
    vi: 'Dừng lại',
    th: 'หยุด',
    ru: 'Остановить',
    id: 'Berhenti',
  } as Str,

  // ── Catch ─────────────────────────────────────────────────────────────
  catchResult: {
    ko: '대단해요!',
    en: 'AMAZING!',
    ja: 'すごい！',
    zh: '太棒了！',
    vi: 'TUYỆT VỜI!',
    th: 'เยี่ยมมาก!',
    ru: 'ПОТРЯСАЮЩЕ!',
    id: 'LUAR BIASA!',
  } as Str,
  catchCount: {
    ko: '개의 감귤을 받았어요',
    en: 'tangerines caught',
    ja: '個のみかんをキャッチ',
    zh: '个柑橘已接住',
    vi: 'quả quýt đã hứng',
    th: 'ลูกที่รับได้',
    ru: 'мандаринов поймано',
    id: 'jeruk tertangkap',
  } as Str,
  tangerineMaster: {
    ko: '감귤 마스터',
    en: 'Tangerine Master',
    ja: 'みかんマスター',
    zh: '柑橘大师',
    vi: 'Bậc thầy hứng quýt',
    th: 'เจ้าแห่งส้ม',
    ru: 'Мастер мандаринов',
    id: 'Master Jeruk',
  } as Str,

  // ── Dodge ─────────────────────────────────────────────────────────────
  dodgeResult: {
    ko: '게임 오버',
    en: 'GAME OVER',
    ja: 'ゲームオーバー',
    zh: '游戏结束',
    vi: 'KẾT THÚC',
    th: 'จบเกม',
    ru: 'ИГРА ОКОНЧЕНА',
    id: 'PERMAINAN SELESAI',
  } as Str,
  dodgeSurvived: {
    ko: '끝까지 살아남았어요!',
    en: 'You survived!',
    ja: '最後まで生き残りました！',
    zh: '你坚持到了最后！',
    vi: 'Bạn đã sống sót!',
    th: 'คุณรอดมาได้!',
    ru: 'Вы выстояли!',
    id: 'Kamu selamat!',
  } as Str,
  dodgeCount: {
    ko: '개의 돌을 피했어요',
    en: 'rocks dodged',
    ja: '個の石をよけました',
    zh: '块石头已躲开',
    vi: 'viên đá đã né',
    th: 'ก้อนที่หลบได้',
    ru: 'камней увернулись',
    id: 'batu dihindari',
  } as Str,

  // ── Pose ──────────────────────────────────────────────────────────────
  copyThePose: {
    ko: '포즈를 따라 하세요!',
    en: 'COPY THE POSE!',
    ja: 'ポーズを真似して！',
    zh: '模仿这个姿势！',
    vi: 'HÃY BẮT CHƯỚC!',
    th: 'ทำท่าตาม!',
    ru: 'ПОВТОРИТЕ ПОЗУ!',
    id: 'TIRUKAN POSE!',
  } as Str,
  poseMatch: {
    ko: '포즈 일치도',
    en: 'POSE MATCH',
    ja: 'ポーズ一致度',
    zh: '姿势匹配度',
    vi: 'ĐỘ KHỚP',
    th: 'ความตรงท่า',
    ru: 'СОВПАДЕНИЕ',
    id: 'KECOCOKAN',
  } as Str,
  perfect: {
    ko: '완벽해요!',
    en: 'PERFECT!',
    ja: 'パーフェクト！',
    zh: '完美！',
    vi: 'HOÀN HẢO!',
    th: 'เพอร์เฟกต์!',
    ru: 'ИДЕАЛЬНО!',
    id: 'SEMPURNA!',
  } as Str,
  great: {
    ko: '훌륭해요!',
    en: 'GREAT!',
    ja: 'すばらしい！',
    zh: '很棒！',
    vi: 'TUYỆT!',
    th: 'เยี่ยม!',
    ru: 'ОТЛИЧНО!',
    id: 'HEBAT!',
  } as Str,
  good: {
    ko: '좋아요!',
    en: 'GOOD!',
    ja: 'いいね！',
    zh: '不错！',
    vi: 'TỐT!',
    th: 'ดี!',
    ru: 'ХОРОШО!',
    id: 'BAGUS!',
  } as Str,
  almost: {
    ko: '아쉬워요!',
    en: 'Almost!',
    ja: '惜しい！',
    zh: '差一点！',
    vi: 'Suýt nữa!',
    th: 'เกือบแล้ว!',
    ru: 'Почти!',
    id: 'Hampir!',
  } as Str,
  poseMaster: {
    ko: '제주 포즈 마스터!',
    en: 'JEJU POSE MASTER!',
    ja: '済州ポーズマスター！',
    zh: '济州姿势大师！',
    vi: 'BẬC THẦY TẠO DÁNG JEJU!',
    th: 'เจ้าแห่งโพสท่าเชจู!',
    ru: 'МАСТЕР ПОЗ ЧЕДЖУ!',
    id: 'MASTER POSE JEJU!',
  } as Str,
  averageMatch: {
    ko: '평균 일치도',
    en: 'average match',
    ja: '平均一致度',
    zh: '平均匹配度',
    vi: 'độ khớp trung bình',
    th: 'ความตรงเฉลี่ย',
    ru: 'среднее совпадение',
    id: 'kecocokan rata-rata',
  } as Str,

  // ── Pose names ────────────────────────────────────────────────────────
  poseHareubang: {
    ko: '돌하르방',
    en: 'Dol Hareubang',
    ja: 'トルハルバン',
    zh: '石头爷爷',
    vi: 'Dol Hareubang',
    th: 'ทลฮารึบัง',
    ru: 'Тольхарубан',
    id: 'Dol Hareubang',
  } as Str,
  poseSunshine: {
    ko: '제주 햇살',
    en: 'Jeju Sunshine',
    ja: '済州の陽ざし',
    zh: '济州阳光',
    vi: 'Nắng Jeju',
    th: 'แดดเชจู',
    ru: 'Солнце Чеджу',
    id: 'Mentari Jeju',
  } as Str,
  poseOcean: {
    ko: '푸른 바다',
    en: 'Blue Ocean',
    ja: '青い海',
    zh: '蔚蓝大海',
    vi: 'Biển Xanh',
    th: 'ทะเลสีคราม',
    ru: 'Синее море',
    id: 'Samudra Biru',
  } as Str,
  poseHaenyeo: {
    ko: '해녀',
    en: 'Haenyeo Diver',
    ja: '海女',
    zh: '海女',
    vi: 'Nữ thợ lặn Haenyeo',
    th: 'แฮนยอ',
    ru: 'Хэнё',
    id: 'Haenyeo',
  } as Str,
  poseHorse: {
    ko: '제주 조랑말',
    en: 'Jeju Pony',
    ja: '済州の馬',
    zh: '济州小马',
    vi: 'Ngựa Jeju',
    th: 'ม้าเชจู',
    ru: 'Пони Чеджу',
    id: 'Kuda Jeju',
  } as Str,
} as const;
