#!/usr/bin/env node
/**
 * Regenerates the display-video manifest from the per-location video folders.
 *
 *   npm run sync:videos
 *
 * Videos live in resources/videos/<set>/ (set = insadong | hwaseong | osaek)
 * and ship as electron-builder extraResources (the whole resources/videos tree).
 * They are streamed at runtime via media://video/<set>/<name>; the renderer only
 * needs the per-set file-name lists so it can resolve clips for the active kiosk.
 */
import { readdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'src/renderer/src/assets/videos/manifest.ts');
const SETS = ['insadong', 'hwaseong', 'osaek'];

async function listSet(set) {
  const dir = join(ROOT, 'resources/videos', set);
  if (!existsSync(dir)) return [];
  return (await readdir(dir)).filter((f) => /\.(mp4|webm)$/i.test(f)).sort();
}

const lists = {};
for (const set of SETS) lists[set] = await listSet(set);

const block = (name, files) =>
  `export const ${name}: string[] = [\n${files.map((f) => `  ${JSON.stringify(f)},`).join('\n')}\n];\n`;

const out =
  `// AUTO-GENERATED by scripts/sync-videos.mjs — do not edit by hand.\n` +
  `// Run \`npm run sync:videos\` after changing resources/videos/<set>/.\n\n` +
  `/** Display video file names per location set, served via media://video/<set>/<name>. */\n` +
  block('VIDEO_FILES_INSADONG', lists.insadong) +
  '\n' +
  block('VIDEO_FILES_HWASEONG', lists.hwaseong) +
  '\n' +
  block('VIDEO_FILES_OSAEK', lists.osaek);

await writeFile(OUT, out, 'utf8');
console.log(
  `✓ video manifest: insadong ${lists.insadong.length}, hwaseong ${lists.hwaseong.length}, osaek ${lists.osaek.length}`,
);
