#!/usr/bin/env node
/**
 * Pulls the kiosk content Google Sheet and generates typed data modules.
 *
 *   npm run sync:sheet
 *
 * Tabs consumed (4-language subset: ko / en / ja / zh):
 *   Localization_Insa  → src/renderer/src/data/localization.generated.ts
 *   PalaceInfo_Insa    → src/renderer/src/data/palaces.generated.ts
 *   AICategory_Insa    → src/renderer/src/data/aiCategories.generated.ts
 *
 * Raw CSVs are cached under src/renderer/src/data/sheet-cache/ so the build
 * still works offline; pass --offline to regenerate from the cache only.
 */
import { mkdir, writeFile, readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const SHEET_ID = '1AVZoyepjrlWIUtwXamGRYU6TWkKKKgVb7fzwEtbRDaw';
/** W004 오산 오색시장 content sheet (tabs suffixed _Osaek). */
const OSAEK_SHEET_ID = '1_CkWFXfB7ud0sJw-cnIWGvFlTzF12UxDuNylp5HkOiw';
const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DATA_DIR = join(ROOT, 'src/renderer/src/data');
const CACHE_DIR = join(DATA_DIR, 'sheet-cache');
const OFFLINE = process.argv.includes('--offline');

const csvUrl = (sheet, sheetId = SHEET_ID) =>
  `https://docs.google.com/spreadsheets/d/${sheetId}/gviz/tq?tqx=out:csv&sheet=${encodeURIComponent(sheet)}`;

/** RFC-4180 CSV parser (handles quoted fields, escaped quotes, embedded newlines). */
function parseCSV(text) {
  const rows = [];
  let row = [];
  let field = '';
  let inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i++; } else inQuotes = false;
      } else field += c;
    } else if (c === '"') inQuotes = true;
    else if (c === ',') { row.push(field); field = ''; }
    else if (c === '\r') { /* ignore */ }
    else if (c === '\n') { row.push(field); rows.push(row); row = []; field = ''; }
    else field += c;
  }
  if (field.length > 0 || row.length > 0) { row.push(field); rows.push(row); }
  return rows;
}

async function loadTab(sheet, sheetId = SHEET_ID) {
  const cacheFile = join(CACHE_DIR, `${sheet}.csv`);
  if (OFFLINE) return parseCSV(await readFile(cacheFile, 'utf8'));
  const res = await fetch(csvUrl(sheet, sheetId));
  if (!res.ok) throw new Error(`Fetch ${sheet} failed: HTTP ${res.status}`);
  const text = await res.text();
  await writeFile(cacheFile, text, 'utf8');
  return parseCSV(text);
}

const clean = (s) => (s ?? '').replace(/ /g, ' ').trim();
const langText = (ko, en, ja, zh) => ({ ko: clean(ko), en: clean(en), ja: clean(ja), zh: clean(zh) });
/** Strip a leading "12-" group/order prefix from a category label. */
const stripPrefix = (s) => clean(s).replace(/^\s*\d+\s*-\s*/, '');

const BANNER = '// AUTO-GENERATED by scripts/sync-sheet.mjs — do not edit by hand.\n// Run `npm run sync:sheet` to refresh from the Google Sheet.\n';

async function genLocalization() {
  const rows = await loadTab('Localization_Insa');
  // Columns: 0 Num, 1 Key, 2 Korean, 3 English, 4 Japanese, 5 Chinese, ...
  const entries = {};
  for (const r of rows.slice(1)) {
    const key = clean(r[1]);
    if (!key || key === 'Key') continue;
    entries[key] = langText(r[2], r[3], r[4], r[5]);
  }
  const body = Object.entries(entries)
    .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
    .join('\n');
  const out = `${BANNER}import type { LangText } from './types';\n\n/** UI strings keyed by their sheet \`Key\`. */\nexport const LOCALIZATION: Record<string, LangText> = {\n${body}\n};\n`;
  await writeFile(join(DATA_DIR, 'localization.generated.ts'), out, 'utf8');
  return Object.keys(entries).length;
}

async function genPalaces() {
  const rows = await loadTab('PalaceInfo_Insa');
  const palaces = [];
  for (const r of rows.slice(1)) {
    if (!/^\d+$/.test(clean(r[0]))) continue; // data rows are numbered
    palaces.push({
      name: langText(r[1], r[2], r[3], r[4]),
      address: langText(r[5], r[6], r[7], r[8]),
      hashtag: langText(r[9], r[10], r[11], r[12]),
      info: langText(r[13], r[14], r[15], r[16]),
      hours: langText(r[17], r[18], r[19], r[20]),
      highlights: langText(r[21], r[22], r[23], r[24]),
      admission: langText(r[25], r[26], r[27], r[28]),
      phone: clean(r[29]),
    });
  }
  const body = palaces.map((p) => `  ${JSON.stringify(p)},`).join('\n');
  const out = `${BANNER}import type { LangText } from './types';\n\nexport interface PalaceData {\n  name: LangText;\n  address: LangText;\n  hashtag: LangText;\n  info: LangText;\n  hours: LangText;\n  highlights: LangText;\n  admission: LangText;\n  phone: string;\n}\n\n/** 고궁안내 — palace data (one entry per palace). */\nexport const PALACES: PalaceData[] = [\n${body}\n];\n`;
  await writeFile(join(DATA_DIR, 'palaces.generated.ts'), out, 'utf8');
  return palaces.length;
}

async function genAiCategories() {
  const rows = await loadTab('AICategory_Insa');
  const cats = [];
  for (const r of rows.slice(1)) {
    if (!/^\d+$/.test(clean(r[0]))) continue;
    cats.push(langText(stripPrefix(r[1]), stripPrefix(r[2]), stripPrefix(r[3]), stripPrefix(r[4])));
  }
  const body = cats.map((c) => `  ${JSON.stringify(c)},`).join('\n');
  const out = `${BANNER}import type { LangText } from './types';\n\n/** '인사' 뭐하지 (AI검색) — 즐길거리 categories, prefix stripped. */\nexport const AI_CATEGORIES: LangText[] = [\n${body}\n];\n`;
  await writeFile(join(DATA_DIR, 'aiCategories.generated.ts'), out, 'utf8');
  return cats.length;
}

async function genVideoSubtitles() {
  const rows = await loadTab('VideoSubtitle_Insa');
  // Cols: 0 NO, 1 Key, 2 VideoFileName, 3-6 subtitle ko/en/ja/zh,
  //       7-10 label ko/en/ja/zh, 11 condition, 12 desc, 13 numbering.
  const entries = [];
  for (const r of rows.slice(1)) {
    const key = clean(r[1]);
    const file = clean(r[2]);
    if (!key || key === 'Key' || !file) continue;
    entries.push({
      key,
      file,
      subtitle: langText(r[3], r[4], r[5], r[6]),
      label: langText(r[7], r[8], r[9], r[10]),
    });
  }
  const body = entries.map((e) => `  ${JSON.stringify(e)},`).join('\n');
  const out = `${BANNER}import type { LangText } from './types';\n\nexport interface VideoEntry {\n  /** State/screen key (Default, ToEat, Palace, …). */\n  key: string;\n  /** Video file stem (matches resources/videos, minus .mp4). */\n  file: string;\n  subtitle: LangText;\n  label: LangText;\n}\n\n/** AI-model display videos per screen/state, in sheet order. */\nexport const VIDEO_SUBTITLES: VideoEntry[] = [\n${body}\n];\n`;
  await writeFile(join(DATA_DIR, 'videoSubtitles.generated.ts'), out, 'utf8');
  return entries.length;
}

// ─── W004 오산 오색시장 (same column layout, _Osaek tabs, separate sheet) ───────
async function genLocalizationOsaek() {
  const rows = await loadTab('Localization_Osaek', OSAEK_SHEET_ID);
  const entries = {};
  for (const r of rows.slice(1)) {
    const key = clean(r[1]);
    if (!key || key === 'Key') continue;
    entries[key] = langText(r[2], r[3], r[4], r[5]);
  }
  const body = Object.entries(entries)
    .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
    .join('\n');
  const out = `${BANNER}import type { LangText } from './types';\n\n/** W004 오색시장 UI strings keyed by their sheet \`Key\` (Localization_Osaek). */\nexport const LOCALIZATION_OSAEK: Record<string, LangText> = {\n${body}\n};\n`;
  await writeFile(join(DATA_DIR, 'localization-osaek.generated.ts'), out, 'utf8');
  return Object.keys(entries).length;
}

async function genAiCategoriesOsaek() {
  const rows = await loadTab('AICategory_Osaek', OSAEK_SHEET_ID);
  const cats = [];
  for (const r of rows.slice(1)) {
    if (!/^\d+$/.test(clean(r[0]))) continue;
    const ko = stripPrefix(r[1]);
    if (!ko) continue; // skip numbered-but-blank rows so no nameless tiles render
    cats.push(langText(ko, stripPrefix(r[2]), stripPrefix(r[3]), stripPrefix(r[4])));
  }
  const body = cats.map((c) => `  ${JSON.stringify(c)},`).join('\n');
  const out = `${BANNER}import type { LangText } from './types';\n\n/** W004 '정이' 모하지(AI검색) 즐길거리 categories, prefix stripped. */\nexport const AI_CATEGORIES_OSAEK: LangText[] = [\n${body}\n];\n`;
  await writeFile(join(DATA_DIR, 'aiCategories-osaek.generated.ts'), out, 'utf8');
  return cats.length;
}

async function genVideoSubtitlesOsaek() {
  const rows = await loadTab('VideoSubtitle_Osaek', OSAEK_SHEET_ID);
  const entries = [];
  for (const r of rows.slice(1)) {
    const key = clean(r[1]);
    const file = clean(r[2]);
    if (!key || key === 'Key' || !file) continue;
    entries.push({
      key,
      file,
      subtitle: langText(r[3], r[4], r[5], r[6]),
      label: langText(r[7], r[8], r[9], r[10]),
    });
  }
  const body = entries.map((e) => `  ${JSON.stringify(e)},`).join('\n');
  const out = `${BANNER}import type { VideoEntry } from './videoSubtitles.generated';\n\n/** W004 오색시장 AI-model display videos per screen/state, in sheet order. */\nexport const VIDEO_SUBTITLES_OSAEK: VideoEntry[] = [\n${body}\n];\n`;
  await writeFile(join(DATA_DIR, 'videoSubtitles-osaek.generated.ts'), out, 'utf8');
  return entries.length;
}

async function main() {
  await mkdir(CACHE_DIR, { recursive: true });
  const loc = await genLocalization();
  const palaces = await genPalaces();
  const cats = await genAiCategories();
  const videos = await genVideoSubtitles();
  console.log(`✓ localization: ${loc} keys`);
  console.log(`✓ palaces:      ${palaces}`);
  console.log(`✓ aiCategories: ${cats}`);
  console.log(`✓ videoSubtitles: ${videos}`);

  // W004 오산 오색시장 (separate sheet, _Osaek tabs)
  const locO = await genLocalizationOsaek();
  const catsO = await genAiCategoriesOsaek();
  const videosO = await genVideoSubtitlesOsaek();
  console.log(`✓ [osaek] localization: ${locO} keys`);
  console.log(`✓ [osaek] aiCategories: ${catsO}`);
  console.log(`✓ [osaek] videoSubtitles: ${videosO}`);
  console.log(OFFLINE ? '(offline: regenerated from cache)' : '(synced from Google Sheets)');
}

main().catch((e) => {
  console.error('sync-sheet failed:', e.message);
  process.exit(1);
});
